sudo: required
language: ruby
git:
  depth: 2

services:
  - docker

script:
  - docker build -t earvin/rethinkdb .
  - docker images -a
#  - docker login -e="$DOCKER_EMAIL" -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
#  - docker push earvin/rethinkdb
